### ISSUE TITLE
get rid of `ProDy` dependency

### ISSUE THREAD

**Issue by rtviii** [rtviii/riboxyz#19]
```
(ribxzvenv) ᢹ ritual.rtviii[ dev/riboxyz ]  p3 ribd.py etl  --struct 3j7z --ptc_coords  --overwrite                                                                                                [cli_refactor]
Traceback (most recent call last):
  File "/home/rtviii/dev/riboxyz/ribd.py", line 2, in <module>
    from ribd_cli.etl import cmd_etl
  File "/home/rtviii/dev/riboxyz/ribd_cli/etl.py", line 4, in <module>
    from ribctl.ribosome_assets import Assetlist, RibosomeAssets, obtain_assets, obtain_assets_threadpool
  File "/home/rtviii/dev/riboxyz/ribctl/ribosome_assets.py", line 22, in <module>
    from ribctl.tunnel.tunnel import ptc_resdiues_get, ptc_residues_calculate_midpoint
  File "/home/rtviii/dev/riboxyz/ribctl/tunnel/tunnel.py", line 5, in <module>
    from ribctl.lib.msalib import *
  File "/home/rtviii/dev/riboxyz/ribctl/lib/msalib.py", line 13, in <module>
    from prody import MSA, MSAFile, parseMSA
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/prody/__init__.py", line 81, in <module>
    from . import atomic
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/prody/atomic/__init__.py", line 148, in <module>
    from .atom import *
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/prody/atomic/atom.py", line 9, in <module>
    from .pointer import AtomPointer
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/prody/atomic/pointer.py", line 7, in <module>
    from .atomic import Atomic
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/prody/atomic/atomic.py", line 19, in <module>
    with openData('mod_res_map.dat') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/prody/utilities/misctools.py", line 428, in openData
    return open(getDataPath(filename), mode)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/prody/utilities/misctools.py", line 424, in getDataPath
    import pkg_resources
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 572, in _build_master
    ws = cls()
         ^^^^^
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 565, in __init__
    self.add_entry(entry)
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 621, in add_entry
    for dist in find_distributions(entry, True):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1988, in find_distributions
    importer = get_importer(path_item)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pkgutil.py", line 416, in get_importer
    path_item = os.fsdecode(path_item)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 824, in fsdecode
TypeError: expected str, bytes or os.PathLike object, not NoneType
(ribxzvenv) ᢹ ritual.rtviii[ dev/riboxyz ]  pip3 uninstall ProDy                                                                                                                                   [cli_refactor]
Found existing installation: ProDy 2.4.0
Uninstalling ProDy-2.4.0:
  Would remove:
    /home/rtviii/dev/ribxzvenv/bin/evol
    /home/rtviii/dev/ribxzvenv/bin/prody
    /home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/ProDy-2.4.0.dist-info/*
    /home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/prody/*
Proceed (Y/n)? Y
  Successfully uninstalled ProDy-2.4.0
(ribxzvenv) ᢹ ritual.rtviii[ dev/riboxyz ]  pip3 index versions prody                                                                                                                              [cli_refactor]
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
prody (2.4.1)
Available versions: 2.4.1, 2.4.0, 2.3.1, 2.3.0, 2.2.0, 2.1.2, 2.1.1, 2.1.0, 2.0.2, 2.0.1, 2.0, 1.11, 1.10.11, 1.10.10, 1.10.9, 1.10.8, 1.10.7, 1.10.6, 1.10.5, 1.10.4, 1.10.3, 1.10.2, 1.10.0, 1.9.4, 1.9.3, 1.9.2, 1.9.1, 1.9, 1.8.2, 1.8, 1.7, 1.5.1, 1.5.0, 1.4.10, 1.4.9, 1.4.8, 1.4.7, 1.4.6, 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4, 1.3.1, 1.3, 1.2.1, 1.2, 1.1, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9, 0.8.3, 1.8.1v
(ribxzvenv) ᢹ ritual.rtviii[ dev/riboxyz ]  pip3 install prody==2.3.1                                                                                                                              [cli_refactor]
Collecting prody==2.3.1
  Downloading ProDy-2.3.1.tar.gz (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 3.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      numpy is not installed, you can find it at: http://www.numpy.org/
      /tmp/pip-build-env-42s0uq66/overlay/lib/python3.11/site-packages/setuptools/build_meta.py:507: SetuptoolsDeprecationWarning: Running `setup.py` directly as CLI tool is deprecated.
      !!

              ********************************************************************************
              Please avoid using `sys.exit(0)` or similar statements that don't fit in the paradigm of a configuration file.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
      Traceback (most recent call last):
        File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rtviii/dev/ribxzvenv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-42s0uq66/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 398, in prepare_metadata_for_build_wheel
          self._bubble_up_info_directory(metadata_directory, ".egg-info")
        File "/tmp/pip-build-env-42s0uq66/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 367, in _bubble_up_info_directory
          info_dir = self._find_info_directory(metadata_directory, suffix)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-42s0uq66/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 378, in _find_info_directory
          assert len(candidates) == 1, f"Multiple {suffix} directories found"
                 ^^^^^^^^^^^^^^^^^^^^
      AssertionError: Multiple .egg-info directories found
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rtviii** [comment]
#20 Light weight
